### PR TITLE
Fix isInfixOf and breakSubString in Word16

### LINKED ISSUE #195: `System.OsPath.Data.ByteString.Short.Word16.isInfixOf` looks dodgy
I haven't tried anything, but from reading the code, it looks like this is just a re-export from `bytestring`. Consequently, I think it can yield false positives if you were to use it for substring matching of UTF-16.

Is this by intention?

### PR DESCRIPTION
**Pull request by hasufell**
Fixes #195

@Bodigrim @sol

### CODE REVIEW

File: System/OsPath/Data/ByteString/Short/Word16.hs [hunk 1]
```diff
@@ -647,6 +650,23 @@ splitWith p = \(assertEven -> sbs) -> if
...
+
+
+breakSubstring :: ShortByteString -- ^ String to search for
+               -> ShortByteString -- ^ String to search in
+               -> (ShortByteString, ShortByteString) -- ^ Head and tail of string broken at substring
+breakSubstring pat = go mempty
+ where
+    go prefix s = let (h, t)  = GHC.Exts.inline BS.breakSubstring pat s
+                      prefix' = prefix `append` h
+                  in if | even (BS.length prefix') -> (prefix', t)
```
Comment (sol) [inline System/OsPath/Data/ByteString/Short/Word16.hs:665]: I think the length of `prefix` is always even. Consequently the length of `prefix'` is even when the length of `h` is even.

So I guess you could check the length of `h` instead of the length of `prefix'` here, which I think will require less allocation.

File: System/OsPath/Data/ByteString/Short/Word16.hs [hunk 2]
```diff
@@ -647,6 +650,23 @@ splitWith p = \(assertEven -> sbs) -> if
...
+                        | otherwise -> let (p, s') = BS.splitAt (BS.length h + 1) s
+                                       in go p s'
```
Comment (sol) [inline System/OsPath/Data/ByteString/Short/Word16.hs:667]: I'm just eyeballing this code, so I may miss the obvious here, but shouldn't this be `go (prefix <> p) s'`?

File: System/OsPath/Data/ByteString/Short/Word16.hs [hunk 3]
```diff
@@ -647,6 +650,23 @@ splitWith p = \(assertEven -> sbs) -> if
...
+
+
+breakSubstring :: ShortByteString -- ^ String to search for
+               -> ShortByteString -- ^ String to search in
+               -> (ShortByteString, ShortByteString) -- ^ Head and tail of string broken at substring
+breakSubstring pat inp = go 0 inp
+ where
+    go prefix s = let (h, t)  = BS.breakSubstring pat s
+                      hl      = BS.length h
+                  in if | even hl   -> (BS.take (hl + prefix) inp, t)
```
Comment (sol) [inline System/OsPath/Data/ByteString/Short/Word16.hs:665]: Another thing that you could do  is to optimize the case where we are done while `prefix` is still `0`. Here you could just return `(h, t)` without any additional `take`. Not sure if it's worth the extra complexity.

**Review by sol — APPROVED** [review]
This looks nice.

File: System/OsPath/Data/ByteString/Short/Word16.hs [hunk 4]
```diff
@@ -647,6 +650,22 @@ splitWith p = \(assertEven -> sbs) -> if
...
+
+breakSubstring :: ShortByteString -- ^ String to search for
+               -> ShortByteString -- ^ String to search in
+               -> (ShortByteString, ShortByteString) -- ^ Head and tail of string broken at substring
+breakSubstring pat = go mempty
+ where
+    go prefix s = let (h, t)  = GHC.Exts.inline BS.breakSubstring pat s
+                  in if | even (BS.length h) -> (prefix `append` h, t)
+                        | otherwise -> let (p, s') = BS.splitAt (BS.length h + 1) s
+                                       in go (prefix `append` p) s'
```
[the remark this answers is not in the document]
Comment (sol) [reply System/OsPath/Data/ByteString/Short/Word16.hs]: > you can probably rely on the fact that `B.breakSubstring` return slices of the original string

Is this indeed the case? Can a `ShortByteString` be sliced?

[the remark this answers is not in the document]
Comment (sol) [reply System/OsPath/Data/ByteString/Short/Word16.hs]: OK, so I think the root of the confusion is that @hasufell linked to `Data.ByteString` instead of `Data.ByteString.Short` at https://github.com/haskell/filepath/issues/195#issuecomment-1604069469.

@Bodigrim @hasufell is that the case?

File: System/OsPath/Data/ByteString/Short/Word16.hs [hunk 5]
```diff
@@ -647,6 +650,26 @@ splitWith p = \(assertEven -> sbs) -> if
...
+isInfixOf sbs = \s -> null sbs || not (null $ snd $ GHC.Exts.inline breakSubstring sbs s)
+
+
+-- algorithm: https://github.com/haskell/filepath/issues/195#issuecomment-1605633713
+breakSubstring :: ShortByteString -- ^ String to search for
+               -> ShortByteString -- ^ String to search in
+               -> (ShortByteString, ShortByteString) -- ^ Head and tail of string broken at substring
+breakSubstring pat inp = go 0 inp
+ where
+    go prefix s = let (h, t)  = BS.breakSubstring pat s
```
Comment (sol) [inline System/OsPath/Data/ByteString/Short/Word16.hs:664]: Use `Data.ByteString.breakSubstring` here.

File: System/OsPath/Data/ByteString/Short/Word16.hs [hunk 6]
```diff
@@ -647,6 +650,26 @@ splitWith p = \(assertEven -> sbs) -> if
...
+                      hl      = BS.length h
+                  in if | even hl   -> if prefix == 0
+                                       then (h, t)
+                                       else (BS.take (hl + prefix) inp, t)
+                        | otherwise -> let (p, s') = BS.splitAt (hl + 1) s
```
Comment (sol) [inline System/OsPath/Data/ByteString/Short/Word16.hs:669]: Use `Data.ByteString.splitAt` here.

File: System/OsPath/Data/ByteString/Short/Word16.hs (hunk 4 above)
[the remark this answers is not in the document]
Comment (hasufell) [reply System/OsPath/Data/ByteString/Short/Word16.hs]: ShortByteString makes copies.

File: System/OsPath/Data/ByteString/Short/Word16.hs [hunk 7]
```diff
@@ -647,6 +650,26 @@ splitWith p = \(assertEven -> sbs) -> if
...
+breakSubstring :: ShortByteString -- ^ String to search for
+               -> ShortByteString -- ^ String to search in
+               -> (ShortByteString, ShortByteString) -- ^ Head and tail of string broken at substring
+breakSubstring pat inp = go 0 inp
+ where
+    go prefix s = let (h, t)  = BS.breakSubstring pat s
+                      hl      = BS.length h
+                  in if | even hl   -> if prefix == 0
+                                       then (h, t)
+                                       else (BS.take (hl + prefix) inp, t)
```
Comment (sol) [inline System/OsPath/Data/ByteString/Short/Word16.hs:668]: Use `Data.ByteString.Short.splitAt` on the original input here to construct the final result:
```haskell
    else BS.splitAt (hl + prefix) inp
```

The special case for `prefix == 0` does not buy us anything anymore and can be removed. `t` can be ignored.

**Review by sol — CHANGES_REQUESTED** [review]
We repeatedly use `Data.ByteString.Short.breakSubstring` and `Data.ByteString.Short.splitAt` which both copy. See: https://github.com/haskell/filepath/pull/199#discussion_r1251144958

I think we will get more predictable performance characteristics if we convert to a `ByteString` first, calculate the offset, and then do a final `splitAt` on the original input.

@Bodigrim any more  thoughts on this?

**Comment by hasufell** [comment]
> We repeatedly use `Data.ByteString.Short.breakSubstring` and `Data.ByteString.Short.splitAt` which both copy. See: [#199 (comment)](https://github.com/haskell/filepath/pull/199#discussion_r1251144958)
> 
> I think we will get more predictable performance characteristics if we convert to a `ByteString` first, calculate the offset, and then do a final `splitAt` on the original input.
> 
> @Bodigrim any more thoughts on this?

I don't think I agree.

The point of ShortByteString is that it doesn't use pinned memory and doesn't contribute to memory fragmentation. Even if the ByteString here will be temporary, I find it morally wrong to use it inside the ShortByteString module.

**Comment by hasufell** [comment]
@Bodigrim done

File: System/OsPath/Data/ByteString/Short/Internal.hs [hunk 8]
```diff
@@ -441,3 +449,29 @@ errorEmptySBS fun = moduleError fun "empty ShortByteString"
 moduleError :: HasCallStack => String -> String -> a
 moduleError fun msg = error (moduleErrorMsg fun msg)
 {-# NOINLINE moduleError #-}
+
+compareByteArraysOff :: BA  -- ^ array 1
```
Comment (hasufell) [inline System/OsPath/Data/ByteString/Short/Internal.hs:453]: Unfortunately, bytestring doesn't expose this internal and we need to to be compatible with GHC-8.2.2 and lower.
